### ISSUE TITLE
Convergence error with higher parameter values

### ISSUE THREAD

**Issue by DavidBrust** [DavidBrust/GasDiffusionElectrodes#12]
I added a notebook that begins to implement [two phase flow in porous media](https://github.com/DavidBrust/GasDiffusionElectrodes/blob/main/notebooks/Porous2Phase.jl) as outlined in your [paper](https://iopscience.iop.org/article/10.1149/1.1572150/meta).

For values of the saturation parameter $\alpha \geq 4.0e-5$, that controls the slope of the capillary pressure/ saturation curve (see below), I run into convergence problems (LinearAlgebra.SingularException(0) @umfpack.jl:203).

![sat_curves(1)](https://user-images.githubusercontent.com/74073919/205306430-479f3e37-0675-4b23-944d-ad2da0e76165.png)

**Comment by j-fu** [comment]
Ok I looked this up in the old code and in the paper.
The point seems to be that for higher parameter values, permeabilities can become zero, so with constant saturation in part of the domain, equations just vanish.

In the paper we described residual saturations, but they are zero besides the one for water in the membrane. Not described in the paper - for whatever reason - is a residual permeability parameter $k_{res}$, one for each phase which regularizes the equations.

Effectively, we used   $k_r =  k_{res} + (1-k_{res}) s^\gamma$
So I would suggest to try this out here.

**Comment by j-fu** [comment]
BTW I still stand by the parametrization of the saturation curve we introduced, though it did not find much traction. I tried to find some newer experimental messurements, the only paper with direct relevance I found is https://doi.org/10.1016/j.apenergy.2018.09.209 . The Büchi group from Paul Scherrer institute also has something: DOI 10.1039/C9CP02149C .
May be there is more.

**Comment by DavidBrust** [comment]
Introducing the residual permeability parameter $k_{res}$ solved the convergence issues that occured previously for higher values of the $\alpha$ parameter. For now I used values of $k_{res,w} = k_{res,g} = 0.001$ for the liquid water and gas phase residual permeabilities respectively, which worked well.

Thanks a lot for the suggestions. I agree that the proposed parametrization of the saturation curve is simple yet adaptable and therefore suitable for implementation in the numerical simulation. Moving forward I will attempt to parametrize experimental data from [10.1016/j.apenergy.2018.09.209](https://doi.org/10.1016/j.apenergy.2018.09.209) accordingly.
