### ISSUE TITLE
Check in Manifest.toml

### ISSUE THREAD

**Issue by j-fu** [DavidBrust/GasDiffusionElectrodes#9]
I wrote some ideas on Julia project stucturs [here](https://j-fu.github.io/marginalia/julia/project-workflow/). 
In particular, checking in the manifest allows to share the code using the exact same package versions.

**Comment by DavidBrust** [comment]
Thanks for the link. I used [PkgTemplates.jl](https://github.com/invenia/PkgTemplates.jl) for the generation of repo, by default the Manifest.toml was in .gitignore. This should be fixed now.
